### 보스턴 회귀분석


In [3]:
import numpy as np
from sklearn.datasets import load_boston

boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [6]:
w = np.linalg.inv(A) @ b
w

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

- 범죄율, 공기오염도, 오래된 정도의 수치가 높을수록 집값이 떨어지고, 방의 개수의 수치가 높을 수록 집값이 올라간다. 

In [7]:
A = ([[1,3,3],
        [1,4,3],
        [1,3,4]])
np.linalg.inv(A)

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

- lstsq 명령을 사용한 보스턴 회귀분석

In [ ]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [11]:
x, resid, rank, s = np.linalg.lstsq(X, y)
x

S:\Teo_install\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])