### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray, np.array(iterable)
- 행렬의 생성 2 : ones, zeros
- 행렬 데이터 선택 : array[x, y, z]
- 행렬 데이터 수정
    - 행렬 데이터를 선택
    - =, < (값(스칼라, 벡터, 행렬))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range 랑 비슷함 : 결과가 ndarray

### quiz
- 100 ~ 138까지 랜덤한 숫자를 가지는 8*8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbx 문자로 변환
- 랜덤한 행렬 데이터

```
datas = np.random.randint(100, 130, size=(8,8))
```

- 데이터 타입을 정수 -> 문자열 : ndarray.astype()

In [2]:
import numpy as np

In [3]:
datas = np.random.randint(100, 130, size=(8,8))
datas

array([[110, 105, 103, 115, 125, 102, 108, 123],
       [115, 119, 106, 118, 118, 128, 115, 125],
       [105, 123, 102, 125, 114, 102, 117, 117],
       [122, 126, 102, 105, 106, 103, 121, 107],
       [106, 105, 107, 118, 112, 100, 117, 114],
       [111, 113, 114, 119, 128, 116, 111, 100],
       [127, 127, 103, 107, 115, 109, 101, 111],
       [117, 119, 101, 105, 102, 117, 122, 114]])

In [4]:
data1 = np.array([1,2,3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [8]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0 
idx_5 = datas % 5 == 0 
idx_15 = datas % 15 == 0 

In [9]:
# 데이터의 타입을 str으로 변환
datas.dtype

dtype('int32')

In [10]:
result = datas.astype("str")
result

array([['110', '105', '103', '115', '125', '102', '108', '123'],
       ['115', '119', '106', '118', '118', '128', '115', '125'],
       ['105', '123', '102', '125', '114', '102', '117', '117'],
       ['122', '126', '102', '105', '106', '103', '121', '107'],
       ['106', '105', '107', '118', '112', '100', '117', '114'],
       ['111', '113', '114', '119', '128', '116', '111', '100'],
       ['127', '127', '103', '107', '115', '109', '101', '111'],
       ['117', '119', '101', '105', '102', '117', '122', '114']],
      dtype='<U11')

In [11]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "bfz"

result

array([['buz', 'bfz', '103', 'buz', 'buz', 'fiz', 'fiz', 'fiz'],
       ['buz', '119', '106', '118', '118', '128', 'buz', 'buz'],
       ['bfz', 'fiz', 'fiz', 'buz', 'fiz', 'fiz', 'fiz', 'fiz'],
       ['122', 'fiz', 'fiz', 'bfz', '106', '103', '121', '107'],
       ['106', 'bfz', '107', '118', '112', 'buz', 'fiz', 'fiz'],
       ['fiz', '113', 'fiz', '119', '128', '116', 'fiz', 'buz'],
       ['127', '127', '103', '107', 'buz', '109', '101', 'fiz'],
       ['fiz', '119', '101', 'bfz', 'fiz', 'fiz', '122', 'fiz']],
      dtype='<U11')

### Quiz
- 1 ~ 20 까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [13]:
q2 = np.random.randint(1,20,(5,5))
q2

array([[ 5, 19,  2, 16, 14],
       [12, 18, 14,  3, 14],
       [ 3, 19, 13, 10,  5],
       [ 2, 10, 16, 15, 10],
       [19, 13, 13,  4,  1]])

In [15]:
min_num, max_num = np.min(q2), np.max(q2)
min_num, max_num

(1, 19)

In [16]:
idx_min = q2 == min_num
idx_max = q2 == max_num

In [20]:
result = q2.astype("str")

result[idx_min] = "MIN"
result[idx_max] = "MAX"

result

array([['5', 'MAX', '2', '16', '14'],
       ['12', '18', '14', '3', '14'],
       ['3', 'MAX', '13', '10', '5'],
       ['2', '10', '16', '15', '10'],
       ['MAX', '13', '13', '4', 'MIN']], dtype='<U11')