### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray, np.array(iterable)
- 행렬의 생성 2 : ones, zeros
- 행렬 데이터 선택 : array[x, y, z]
- 행렬 데이터 수정
    - 행렬 데이터를 선택
    - =, < (값(스칼라, 벡터, 행렬))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range 랑 비슷함 : 결과가 ndarray

### quiz
- 100 ~ 138까지 랜덤한 숫자를 가지는 8*8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbx 문자로 변환
- 랜덤한 행렬 데이터

```
datas = np.random.randint(100, 130, size=(8,8))
```

- 데이터 타입을 정수 -> 문자열 : ndarray.astype()

In [1]:
import numpy as np

In [3]:
datas = np.random.randint(100, 130, size=(8,8))
datas

array([[110, 105, 103, 115, 125, 102, 108, 123],
       [115, 119, 106, 118, 118, 128, 115, 125],
       [105, 123, 102, 125, 114, 102, 117, 117],
       [122, 126, 102, 105, 106, 103, 121, 107],
       [106, 105, 107, 118, 112, 100, 117, 114],
       [111, 113, 114, 119, 128, 116, 111, 100],
       [127, 127, 103, 107, 115, 109, 101, 111],
       [117, 119, 101, 105, 102, 117, 122, 114]])

In [4]:
data1 = np.array([1,2,3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [8]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0 
idx_5 = datas % 5 == 0 
idx_15 = datas % 15 == 0 

In [9]:
# 데이터의 타입을 str으로 변환
datas.dtype

dtype('int32')

In [10]:
result = datas.astype("str")
result

array([['110', '105', '103', '115', '125', '102', '108', '123'],
       ['115', '119', '106', '118', '118', '128', '115', '125'],
       ['105', '123', '102', '125', '114', '102', '117', '117'],
       ['122', '126', '102', '105', '106', '103', '121', '107'],
       ['106', '105', '107', '118', '112', '100', '117', '114'],
       ['111', '113', '114', '119', '128', '116', '111', '100'],
       ['127', '127', '103', '107', '115', '109', '101', '111'],
       ['117', '119', '101', '105', '102', '117', '122', '114']],
      dtype='<U11')

In [11]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "bfz"

result

array([['buz', 'bfz', '103', 'buz', 'buz', 'fiz', 'fiz', 'fiz'],
       ['buz', '119', '106', '118', '118', '128', 'buz', 'buz'],
       ['bfz', 'fiz', 'fiz', 'buz', 'fiz', 'fiz', 'fiz', 'fiz'],
       ['122', 'fiz', 'fiz', 'bfz', '106', '103', '121', '107'],
       ['106', 'bfz', '107', '118', '112', 'buz', 'fiz', 'fiz'],
       ['fiz', '113', 'fiz', '119', '128', '116', 'fiz', 'buz'],
       ['127', '127', '103', '107', 'buz', '109', '101', 'fiz'],
       ['fiz', '119', '101', 'bfz', 'fiz', 'fiz', '122', 'fiz']],
      dtype='<U11')

### Quiz
- 1 ~ 20 까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [13]:
q2 = np.random.randint(1,20,(5,5))
q2

array([[ 5, 19,  2, 16, 14],
       [12, 18, 14,  3, 14],
       [ 3, 19, 13, 10,  5],
       [ 2, 10, 16, 15, 10],
       [19, 13, 13,  4,  1]])

In [15]:
min_num, max_num = np.min(q2), np.max(q2)
min_num, max_num

(1, 19)

In [16]:
idx_min = q2 == min_num
idx_max = q2 == max_num

In [20]:
result = q2.astype("str")

result[idx_min] = "MIN"
result[idx_max] = "MAX"

result

array([['5', 'MAX', '2', '16', '14'],
       ['12', '18', '14', '3', '14'],
       ['3', 'MAX', '13', '10', '5'],
       ['2', '10', '16', '15', '10'],
       ['MAX', '13', '13', '4', 'MIN']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [2]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [3]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [ ]:
# 30세에 연봉이 $100,000 이고, 60세의 연봉이 $1,000,000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세 50세 연봉을 출력

In [10]:
age30 = 100000
age60 = 1000000

In [11]:
np.linspace(age30, age60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [13]:
np.logspace(np.log10(age30), np.log10(age60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy  random
- seed : 랜덤값을 설정함
- rand : 균등분포로 랜덤한 값 생성
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어 준다.
- choice : 특정 확률로 데이터를 선택

In [14]:
# seed
np.random.seed(1)
result1 = np.random.randint(10,100,10)

np.random.seed(1)
result2 = np.random.randint(10,100,10)

np.random.seed(2)
result3 = np.random.randint(10,100,10)

np.mean(result1), np.mean(result2), np.mean(result3)

(47.0, 47.0, 53.9)

In [15]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [16]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [17]:
# shuffle
r= np.random.randint(1, 10, (3,4))
r

array([[2, 8, 9, 3],
       [9, 8, 2, 7],
       [9, 6, 4, 1]])

In [21]:
r = np.reshape(r, 12)
np.random.shuffle(r)
r = np.reshape(r, (3,4))
r

array([[2, 9, 1, 8],
       [9, 2, 6, 9],
       [8, 4, 3, 7]])

In [28]:
# choice
np.random.choice(5,10,p=[0.1, 0, 0.4, 0.2, 0.3])

array([3, 2, 2, 2, 4, 2, 4, 2, 0, 0], dtype=int64)

In [30]:
# unipue
numbers ,counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[1 2 3 4 6 7 8 9]
[1 2 1 1 1 1 2 3]


### 3. 행렬 데이터의 결합
- concatenate

In [40]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(3,2))
na3 = np.random.randint(10, size=(3,3))

In [41]:
na1

array([[5, 1, 5],
       [9, 4, 9]])

In [42]:
na2

array([[8, 3],
       [4, 6],
       [2, 4]])

In [43]:
na3

array([[7, 5, 1],
       [3, 7, 4],
       [5, 1, 2]])

In [44]:
# 세로결합
np.concatenate((na1, na3))

array([[5, 1, 5],
       [9, 4, 9],
       [7, 5, 1],
       [3, 7, 4],
       [5, 1, 2]])

In [46]:
# 가로결합
np.concatenate((na2, na3), axis=1)

array([[8, 3, 7, 5, 1],
       [4, 6, 3, 7, 4],
       [2, 4, 5, 1, 2]])

In [47]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])