### Numpy
- 데이터는 행렬로 표현
- 행렬데이터를 빠르게 계산을 해야 합니다.
- 행렬 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 메트릭스

In [1]:
import numpy as np

In [ ]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [2]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [4]:
array2 = np.array(
[[1,2,3],
 [4,5,6]],
)
type(array2), array2, array2.shape

(numpy.ndarray,
 array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [10]:
# 행렬의 모양(shape) 변경하기
array2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# 행렬 데이터의 선택 : offset index : masking

In [18]:
array2[1][::-1]

array([6, 5, 4])

In [19]:
array2[1,-1] # array2[1][-1] 

6

In [ ]:
# 데이터 수정

In [20]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [21]:
array2[1,-1] = 99

In [23]:
array2[0] = 77

In [24]:
array2

array([[77, 77, 77],
       [ 4,  5, 99]])

In [25]:
array2[0] = [1,2,3]

In [26]:
array2

array([[ 1,  2,  3],
       [ 4,  5, 99]])

In [30]:
idx = array2 > 3
idx

array([[False, False, False],
       [ True,  True,  True]])

In [31]:
array2[idx]

array([  4,   5, 100])

In [32]:
array2[idx] = 100
array2

array([[  1,   2,   3],
       [100, 100, 100]])

In [ ]:
# 행렬 데이터의 생성 2

In [34]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
data.dtype

dtype('float64')

In [38]:
data2=data.astype("int")
data2.dtype

dtype('int32')

In [43]:
data = np.ones((2,3,2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [40]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.arange(5,10,2)

array([5, 7, 9])